### 获取当前用户余额信息
GET http://127.0.0.1:9001/gateway/ecommerce-account-service/balance/current-balance
Accept: application/json
commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJjb21tZXJjZS11c2VyIjoie1wiaWRcIjoxMCxcInVzZXJuYW1lXCI6XCJ0b21cIn0iLCJqdGkiOiJmMGUxNDE0ZS1hYTQyLTRiYjQtYWIwMC0yOGMxMTNjMjAzZTkiLCJleHAiOjE2Njg1ODA5MzF9.nOV4wUZFO3JLWf-rvDPEqmpGNO5YfqGoYqmYdqLnpaSqHz6IKzoB4lGpcmv7P98iQwNiHw2dEpBe59LKACKiUEOI5mr9H4071ie5odtCxgfOD615sg-mjgjFsnGzvcr7DZdpDF-YiQjUKg_6rIk7-OqXNeJjbzkjYKm0KhAA0zPYpyhZFPzW1BQ6X32iXiL7278Xo7jgLiLaTAOIuo0mPhYzmOCALtPidFWISaAiEAzYszhzXOnRBUAmbgeplCkbH9zVO9WUsOWkdChzVgA6QIDUb63u6BbCZdVqVtbN9imOOJVubdSxwhOju9QKeqrS0WxEXza6Itm7qnsZdabTrQ
token: imooc

### 扣减用户余额
PUT http://127.0.0.1:9001/gateway/ecommerce-account-service/balance/deduct-balance
Content-Type: application/json
commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJjb21tZXJjZS11c2VyIjoie1wiaWRcIjoxMCxcInVzZXJuYW1lXCI6XCJ0b21cIn0iLCJqdGkiOiJmMGUxNDE0ZS1hYTQyLTRiYjQtYWIwMC0yOGMxMTNjMjAzZTkiLCJleHAiOjE2Njg1ODA5MzF9.nOV4wUZFO3JLWf-rvDPEqmpGNO5YfqGoYqmYdqLnpaSqHz6IKzoB4lGpcmv7P98iQwNiHw2dEpBe59LKACKiUEOI5mr9H4071ie5odtCxgfOD615sg-mjgjFsnGzvcr7DZdpDF-YiQjUKg_6rIk7-OqXNeJjbzkjYKm0KhAA0zPYpyhZFPzW1BQ6X32iXiL7278Xo7jgLiLaTAOIuo0mPhYzmOCALtPidFWISaAiEAzYszhzXOnRBUAmbgeplCkbH9zVO9WUsOWkdChzVgA6QIDUb63u6BbCZdVqVtbN9imOOJVubdSxwhOju9QKeqrS0WxEXza6Itm7qnsZdabTrQ
{
  "userId": 10,
  "balance": 2000
}
