spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/content_center?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root123456

  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: 172.16.200.249:8848
        namespace: 1cbd4445-e494-4011-bccb-7ac4c094f9d7
        # NJ 假设南京机房
        cluster-name: NJ
        # 设置实例元数据
        metadata:
          instance: content
          key: 测试
          version: v1
    # sentinel通信
    sentinel:
      transport:
        # sentinel-dashboard-1.6.0 的访问路径 ，启动方式java -jar sentinel-dashboard-1.6.0.jar
        # java -Dserver.port=8082 -jar sentinel-dashboard-1.6.0.jar   默认8080端口
        dashboard: localhost:9100
        client-ip: 172.16.22.197
        heartbeat-interval-ms: 500
      eager: true
  application:
    # 服务名称尽量用-，不要用_，不要用特殊字符
    name: content-center

mybatis-plus:
  mapper-locations:
    - classpath:/mapper/*.xml
    - classpath*:/mapper/**/*.xml

logging:
  level:
    com.example: debug

feign:
  client:
    config:
      # 全局配置(日志)
      default:
        loggerlevel: full

#开启健康检查,开放所有监控指标
management:
  endpoints: #注意是endpoints
    web:
      exposure:
        include: '*'
