ali:
  config:
    accessKeyId: LTAI4G6xynjeASQ7QWiCDxd1
    accessKeySecret: cadE9VpjEsSUD1smalGCVQdaC5goI6
    sms:
      signName: \u963F\u91CC\u4E91\u77ED\u4FE1\u6D4B\u8BD5
      templateCode: SMS_154950909