server:
  port: 8082
  servlet:
    context-path: /demo

xxl:
  job:
    admin:
      addresses: http://localhost:18080/xxl-job-admin/
    executor:
      appname: xxl-job-executor-sample
      logpath: /tmp/
#spring:
#  mvc:
#    servlet:
#      path: /demo
