aliyun:
  oss:
    bucket:
    endpoint:
    accessKeyId:
    accessKeySecret:

#系统业务参数
isys:

  oss:
    file-root-path: /Users/wanggaoshuai/develop/upload #存储根路径 ( 无需以‘/’结尾 )
    file-public-path: ${isys.oss.file-root-path}/public #公共读取块  ( 一般配合root-path参数进行设置，需以‘/’ 开头, 无需以‘/’结尾 )
    file-private-path: ${isys.oss.file-root-path}/private #私有化本地访问，不允许url方式公共读取 ( 一般配合root-path参数进行设置，需以‘/’ 开头, 无需以‘/’结尾  )

    # [local]: 本地存储，所有的文件将存在放本地，可通过nfs, rsync工具实现多机共享；
    # [aliyun-oss]: 将文件统一上传到阿里云oss服务器;
    # [qiniu-oss]: 将文件统一上传到七牛云oss服务器;
    service-type: qiniu-oss

    # 阿里云OSS服务配置信息
    aliyun-oss:
      endpoint: oss-us-west-1.aliyuncs.com  #endpoint  如： oss-cn-beijing.aliyuncs.com
      public-bucket-name: inparkserver #公共读 桶名称
      private-bucket-name: inparkserver  #私有 桶名称
      access-key-id: LTAI5tApjwUBpNV3KuUg26AT   #AccessKeyId
      access-key-secret: S9n9q7bNI2bt01dk0Epcy2wvEFBJas  #AccessKeySecret
    qiniu-oss:
      ak: k78TmLqWbytGbOY1xpyEbguXOkAgjaeOVLoJ4FlD # ak
      sk: sXrxQItLMGZZ9qOpii2YmrEw5hRQucHW-p7k-qRI # sk
      bucket: gbw # 桶名称
