mail:
  # \u8FC7\u6EE4\u5F00\u5173
  enabled: true
  # SMTP\u670D\u52A1\u5668\u57DF\u540D
  host: smtp.yeah.net
  # \u7AEF\u53E3\u53F7
  port: 465
  # \u662F\u5426\u9700\u8981\u7528\u6237\u540D\u5BC6\u7801\u9A8C\u8BC1
  auth: true
  user: wgshuaiit
  pass:
  from:
  starttlsEnable: false
  sslEnable: true
