server:
  port: 8081

spring:
  application:
    name: sequence
  datasource:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/jfinal_demo?useSSL=false&useUnicode=true&characterEncoding=UTF-8
#      username: root
#      password: root123456
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/jfinal_demo?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root123456


mybatis-plus:
  mapper-locations:
    - classpath:/mapper/*.xml
    - classpath*:/mapper/**/*.xml

logging:
  level:
    com.example: debug

knife4j:
  enable: true
  openapi:
    title: 流水号文档
    description: "`我是测试`,**流水号**"
    email: xiaoymin@foxmail.com
    concat: wgs
    url: https://docs.xiaominfo.com
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    # 选配
#    group:
#      test1:
#        group-name: 商品模块
#        api-rule: package
#        api-rule-resources:
#          - com.example.controller.enterprise
#      test2:
#        group-name: 流水号模块
#        api-rule: package
#        api-rule-resources:
#          - com.example.controller.sequence


# 加密
encrypt:
  # 拦截器是否开启
  interceptor:
    enabled: true
  table-field-map:
    sequence_role:
      - sequenceName
    sys_enterprise:
      - contactPhone
      - legalPersonIdNumber
      - legalPersonPhone
