spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/user_center?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root123456

  cloud:
    nacos:
      discovery:
        # \u6307\u5B9Anacos server\u7684\u5730\u5740
        server-addr: 172.16.200.249:8848
  application:
    # \u670D\u52A1\u540D\u79F0\u5C3D\u91CF\u7528-\uFF0C\u4E0D\u8981\u7528_\uFF0C\u4E0D\u8981\u7528\u7279\u6B8A\u5B57\u7B26
    name: user-center
server:
  port: 8081

mybatis-plus:
  mapper-locations:
    - classpath:/mapper/*.xml
    - classpath*:/mapper/**/*.xml

logging:
  level:
    com.example: debug