spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/user_center?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root123456

  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: 172.16.200.249:8848
        namespace: 1cbd4445-e494-4011-bccb-7ac4c094f9d7
        # NJ 假设南京机房
        cluster-name: NJ
  application:
    # 服务名称尽量用-，不要用_，不要用特殊字符
    name: user-center
server:
  port: 8081

mybatis-plus:
  mapper-locations:
    - classpath:/mapper/*.xml
    - classpath*:/mapper/**/*.xml

logging:
  level:
    com.example: debug