server:
  port: 8040

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        # \u670D\u52A1\u6CE8\u518C\u5730\u5740
        server-addr: 172.16.200.249:8848
        # \u547D\u540D\u7A7A\u95F4
        namespace: 1cbd4445-e494-4011-bccb-7ac4c094f9d7
    gateway:
      discovery:
        locator:
          # 让gateway通过服务发现组件找到其他的微服务
          enabled: true
      routes:
        - id: path_route
          # lb代表从注册中心获取服务，且已负载均衡方式转发
          uri: lb://user-center
          predicates:
            # 当且仅当访问路径是/users/*或者/some-path/**，才会转发用户微服务
            # segment是一个特殊的占位符，单层路径匹配
            # eg. 访问http://localhost:8040/users/1 -> user-center/users/1
            - Path=/user/{segment},/some-path/**
        - id: content-center
          # lb代表从注册中心获取服务，且已负载均衡方式转发
          uri: lb://content-center
          # 当且仅当访问路径是/users/*或者/some-path/**，才会转发用户微服务
          # segment是一个特殊的占位符，单层路径匹配
          # eg. 访问http://localhost:8040/users/1 -> user-center/users/1
          predicates:
            - Path=/content-center/{segment},/some-path/**

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  level:
    com.example: debug
    org.springframework.cloud.gateway: trace