CREATE TABLE `sys_dict` (
                            `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
                            `parent_id` varchar(50) DEFAULT NULL COMMENT '父级id',
                            `group_code` varchar(50) DEFAULT NULL COMMENT '分组编码',
                            `group_name` varchar(255) DEFAULT NULL COMMENT '分组名称',
                            `data_type` varchar(50) NOT NULL COMMENT '数据类别',
                            `data_type_name` varchar(50) NOT NULL COMMENT '数据类别名称',
                            `data_tags` varchar(100) DEFAULT NULL COMMENT '数据标签，多个标签，"|"分割',
                            `data_code` varchar(200) NOT NULL COMMENT '数据编码',
                            `data_name` varchar(200) NOT NULL COMMENT '数据名称',
                            `data_value` varchar(200) NOT NULL COMMENT '数据值',
                            `universal_standard_code` varchar(50) DEFAULT NULL COMMENT '通用标准代码',
                            `remark` varchar(500) DEFAULT NULL COMMENT '备注',
                            `sort` int(11) NOT NULL DEFAULT '1' COMMENT '排序',
                            `allow_edit` int(11) NOT NULL DEFAULT '0' COMMENT '是否允许编辑（0:不允许,1:允许）',
                            `version` bigint(20) NOT NULL DEFAULT '1' COMMENT '版本号',
                            `state` tinyint(4) NOT NULL DEFAULT '1' COMMENT '状态（0：禁用，1：启用）',
                            `is_delete` tinyint(4) NOT NULL DEFAULT '0' COMMENT '删除状态（0：未删除，1：删除）',
                            `create_date_time` datetime NOT NULL COMMENT '创建时间',
                            `create_name` varchar(255) NOT NULL COMMENT '创建人',
                            `modify_date_time` datetime NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
                            `modify_name` varchar(255) NOT NULL COMMENT '修改人',
                            PRIMARY KEY (`id`) USING BTREE,
                            UNIQUE KEY `UK_SYS_DICT` (`data_type`,`data_code`,`is_delete`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=28451 DEFAULT CHARSET=utf8mb4 COMMENT='数据词典';



INSERT INTO `apollo_wenzhou_dev`.`sys_dict` (`id`, `parent_id`, `group_code`, `group_name`, `data_type`, `data_type_name`, `data_tags`, `data_code`, `data_name`, `data_value`, `universal_standard_code`, `remark`, `sort`, `allow_edit`, `version`, `state`, `is_delete`, `create_date_time`, `create_name`, `modify_date_time`, `modify_name`) VALUES (1, 'system', 'project', '工程', 'projectType', '工程项目交易类型', NULL, 'housing_construction', '房建工程', 'housing_construction', NULL, NULL, 1, 1, 1, 1, 0, '2023-09-02 14:46:55', 'sys', '2024-08-29 15:05:47', 'sys');
INSERT INTO `apollo_wenzhou_dev`.`sys_dict` (`id`, `parent_id`, `group_code`, `group_name`, `data_type`, `data_type_name`, `data_tags`, `data_code`, `data_name`, `data_value`, `universal_standard_code`, `remark`, `sort`, `allow_edit`, `version`, `state`, `is_delete`, `create_date_time`, `create_name`, `modify_date_time`, `modify_name`) VALUES (2, 'system', 'project', '工程', 'projectType', '工程项目交易类型', NULL, 'municipal', '市政工程', 'municipal', NULL, NULL, 2, 1, 1, 1, 0, '2023-09-02 14:46:55', 'sys', '2024-08-29 15:05:47', 'sys');
INSERT INTO `apollo_wenzhou_dev`.`sys_dict` (`id`, `parent_id`, `group_code`, `group_name`, `data_type`, `data_type_name`, `data_tags`, `data_code`, `data_name`, `data_value`, `universal_standard_code`, `remark`, `sort`, `allow_edit`, `version`, `state`, `is_delete`, `create_date_time`, `create_name`, `modify_date_time`, `modify_name`) VALUES (3, 'system', 'project', '工程', 'projectType', '工程项目交易类型', NULL, 'traffic', '交通工程', 'traffic', NULL, NULL, 3, 1, 1, 1, 0, '2023-09-02 14:46:55', 'sys', '2024-08-29 15:05:47', 'sys');
INSERT INTO `apollo_wenzhou_dev`.`sys_dict` (`id`, `parent_id`, `group_code`, `group_name`, `data_type`, `data_type_name`, `data_tags`, `data_code`, `data_name`, `data_value`, `universal_standard_code`, `remark`, `sort`, `allow_edit`, `version`, `state`, `is_delete`, `create_date_time`, `create_name`, `modify_date_time`, `modify_name`) VALUES (4, 'system', 'project', '工程', 'projectType', '工程项目交易类型', NULL, 'water_conservancy', '水利工程', 'water_conservancy', NULL, NULL, 4, 1, 1, 1, 0, '2023-09-02 14:46:55', 'sys', '2024-08-29 15:05:47', 'sys');
INSERT INTO `apollo_wenzhou_dev`.`sys_dict` (`id`, `parent_id`, `group_code`, `group_name`, `data_type`, `data_type_name`, `data_tags`, `data_code`, `data_name`, `data_value`, `universal_standard_code`, `remark`, `sort`, `allow_edit`, `version`, `state`, `is_delete`, `create_date_time`, `create_name`, `modify_date_time`, `modify_name`) VALUES (5, 'system', 'project', '工程', 'projectType', '工程项目交易类型', NULL, 'electric_power', '电力工程', 'electric_power', NULL, NULL, 5, 1, 1, 1, 0, '2023-09-02 14:46:55', 'sys', '2024-08-29 15:05:47', 'sys');
INSERT INTO `apollo_wenzhou_dev`.`sys_dict` (`id`, `parent_id`, `group_code`, `group_name`, `data_type`, `data_type_name`, `data_tags`, `data_code`, `data_name`, `data_value`, `universal_standard_code`, `remark`, `sort`, `allow_edit`, `version`, `state`, `is_delete`, `create_date_time`, `create_name`, `modify_date_time`, `modify_name`) VALUES (6, 'system', 'project', '工程', 'projectType', '工程项目交易类型', NULL, 'decoration', '装饰工程', 'decoration', NULL, NULL, 6, 1, 1, 1, 0, '2023-09-02 14:46:55', 'sys', '2024-08-29 15:05:47', 'sys');
INSERT INTO `apollo_wenzhou_dev`.`sys_dict` (`id`, `parent_id`, `group_code`, `group_name`, `data_type`, `data_type_name`, `data_tags`, `data_code`, `data_name`, `data_value`, `universal_standard_code`, `remark`, `sort`, `allow_edit`, `version`, `state`, `is_delete`, `create_date_time`, `create_name`, `modify_date_time`, `modify_name`) VALUES (7, 'system', 'project', '工程', 'projectType', '工程项目交易类型', NULL, 'land', '国土工程', 'land', NULL, NULL, 7, 1, 1, 1, 0, '2023-09-02 14:46:55', 'sys', '2024-08-29 15:05:47', 'sys');
INSERT INTO `apollo_wenzhou_dev`.`sys_dict` (`id`, `parent_id`, `group_code`, `group_name`, `data_type`, `data_type_name`, `data_tags`, `data_code`, `data_name`, `data_value`, `universal_standard_code`, `remark`, `sort`, `allow_edit`, `version`, `state`, `is_delete`, `create_date_time`, `create_name`, `modify_date_time`, `modify_name`) VALUES (9, 'system', 'project', '工程', 'projectType', '工程项目交易类型', NULL, 'landscaping', '园林绿化', 'landscaping', NULL, NULL, 8, 1, 1, 1, 0, '2023-09-02 14:46:55', 'sys', '2024-08-29 15:05:47', 'sys');
INSERT INTO `apollo_wenzhou_dev`.`sys_dict` (`id`, `parent_id`, `group_code`, `group_name`, `data_type`, `data_type_name`, `data_tags`, `data_code`, `data_name`, `data_value`, `universal_standard_code`, `remark`, `sort`, `allow_edit`, `version`, `state`, `is_delete`, `create_date_time`, `create_name`, `modify_date_time`, `modify_name`) VALUES (10, 'system', 'project', '工程', 'projectType', '工程项目交易类型', NULL, 'other', '其他工程', 'other', NULL, NULL, 99, 1, 1, 1, 0, '2023-09-02 14:46:55', 'sys', '2024-08-29 15:05:47', 'sys');
INSERT INTO `apollo_wenzhou_dev`.`sys_dict` (`id`, `parent_id`, `group_code`, `group_name`, `data_type`, `data_type_name`, `data_tags`, `data_code`, `data_name`, `data_value`, `universal_standard_code`, `remark`, `sort`, `allow_edit`, `version`, `state`, `is_delete`, `create_date_time`, `create_name`, `modify_date_time`, `modify_name`) VALUES (11, 'system', 'project', '工程', 'projectLevel', '工程项目级别', NULL, 'village', '村级', 'village', NULL, NULL, 1, 1, 1, 1, 0, '2023-09-02 14:46:55', 'sys', '2024-08-30 10:55:45', 'sys');
INSERT INTO `apollo_wenzhou_dev`.`sys_dict` (`id`, `parent_id`, `group_code`, `group_name`, `data_type`, `data_type_name`, `data_tags`, `data_code`, `data_name`, `data_value`, `universal_standard_code`, `remark`, `sort`, `allow_edit`, `version`, `state`, `is_delete`, `create_date_time`, `create_name`, `modify_date_time`, `modify_name`) VALUES (12, 'system', 'project', '工程', 'projectLevel', '工程项目级别', NULL, 'town', '镇级', 'town', NULL, NULL, 2, 1, 1, 1, 0, '2023-09-02 14:46:55', 'sys', '2024-08-30 10:55:47', 'sys');
INSERT INTO `apollo_wenzhou_dev`.`sys_dict` (`id`, `parent_id`, `group_code`, `group_name`, `data_type`, `data_type_name`, `data_tags`, `data_code`, `data_name`, `data_value`, `universal_standard_code`, `remark`, `sort`, `allow_edit`, `version`, `state`, `is_delete`, `create_date_time`, `create_name`, `modify_date_time`, `modify_name`) VALUES (13, 'system', 'project', '工程', 'projectLevel', '工程项目级别', NULL, 'county', '县级', 'county', NULL, NULL, 3, 1, 1, 1, 0, '2023-09-02 14:46:55', 'sys', '2024-08-30 10:55:47', 'sys');
INSERT INTO `apollo_wenzhou_dev`.`sys_dict` (`id`, `parent_id`, `group_code`, `group_name`, `data_type`, `data_type_name`, `data_tags`, `data_code`, `data_name`, `data_value`, `universal_standard_code`, `remark`, `sort`, `allow_edit`, `version`, `state`, `is_delete`, `create_date_time`, `create_name`, `modify_date_time`, `modify_name`) VALUES (14, 'system', 'project', '工程', 'projectLevel', '工程项目级别', NULL, 'municipal', '市级', 'municipal', NULL, NULL, 4, 1, 1, 1, 0, '2023-09-02 14:46:55', 'sys', '2024-08-30 10:55:47', 'sys');
INSERT INTO `apollo_wenzhou_dev`.`sys_dict` (`id`, `parent_id`, `group_code`, `group_name`, `data_type`, `data_type_name`, `data_tags`, `data_code`, `data_name`, `data_value`, `universal_standard_code`, `remark`, `sort`, `allow_edit`, `version`, `state`, `is_delete`, `create_date_time`, `create_name`, `modify_date_time`, `modify_name`) VALUES (21, 'system', NULL, NULL, 'contractForm', '发包情形', NULL, 'state_owned_founds_hold', '国有资金控股或占主导地位的依法发包', 'state_owned_founds_hold', NULL, NULL, 1, 1, 1, 1, 0, '2023-09-02 14:46:55', 'sys', '2024-08-29 15:05:47', 'sys');
INSERT INTO `apollo_wenzhou_dev`.`sys_dict` (`id`, `parent_id`, `group_code`, `group_name`, `data_type`, `data_type_name`, `data_tags`, `data_code`, `data_name`, `data_value`, `universal_standard_code`, `remark`, `sort`, `allow_edit`, `version`, `state`, `is_delete`, `create_date_time`, `create_name`, `modify_date_time`, `modify_name`) VALUES (22, 'system', NULL, NULL, 'contractForm', '发包情形', NULL, 'voluntary', '自愿发包', 'voluntary', NULL, NULL, 2, 1, 1, 1, 0, '2023-09-02 14:46:55', 'sys', '2024-08-29 15:05:47', 'sys');
INSERT INTO `apollo_wenzhou_dev`.`sys_dict` (`id`, `parent_id`, `group_code`, `group_name`, `data_type`, `data_type_name`, `data_tags`, `data_code`, `data_name`, `data_value`, `universal_standard_code`, `remark`, `sort`, `allow_edit`, `version`, `state`, `is_delete`, `create_date_time`, `create_name`, `modify_date_time`, `modify_name`) VALUES (23, 'system', NULL, NULL, 'contractForm', '发包情形', NULL, 'other', '其他情形的依法发包', 'other', NULL, NULL, 3, 1, 1, 1, 0, '2023-09-02 14:46:55', 'sys', '2024-08-29 15:05:47', 'sys');
INSERT INTO `apollo_wenzhou_dev`.`sys_dict` (`id`, `parent_id`, `group_code`, `group_name`, `data_type`, `data_type_name`, `data_tags`, `data_code`, `data_name`, `data_value`, `universal_standard_code`, `remark`, `sort`, `allow_edit`, `version`, `state`, `is_delete`, `create_date_time`, `create_name`, `modify_date_time`, `modify_name`) VALUES (24, 'system', 'project', '工程', 'contractType', '工程项目交易方式', 'trading', 'public', '公开发包', '1', NULL, NULL, 1, 1, 1, 1, 0, '2023-09-02 14:46:55', 'sys', '2024-08-29 15:05:47', 'sys');
INSERT INTO `apollo_wenzhou_dev`.`sys_dict` (`id`, `parent_id`, `group_code`, `group_name`, `data_type`, `data_type_name`, `data_tags`, `data_code`, `data_name`, `data_value`, `universal_standard_code`, `remark`, `sort`, `allow_edit`, `version`, `state`, `is_delete`, `create_date_time`, `create_name`, `modify_date_time`, `modify_name`) VALUES (25, 'system', 'project', '工程', 'contractType', '工程项目交易方式', 'trading', 'invitation', '邀请发包', '2', NULL, NULL, 2, 1, 1, 1, 0, '2023-09-02 14:46:55', 'sys', '2024-08-29 15:05:47', 'sys');
INSERT INTO `apollo_wenzhou_dev`.`sys_dict` (`id`, `parent_id`, `group_code`, `group_name`, `data_type`, `data_type_name`, `data_tags`, `data_code`, `data_name`, `data_value`, `universal_standard_code`, `remark`, `sort`, `allow_edit`, `version`, `state`, `is_delete`, `create_date_time`, `create_name`, `modify_date_time`, `modify_name`) VALUES (26, 'system', 'project', '工程', 'contractType', '工程项目交易方式', NULL, 'direct_filing', '直发包备案', '13', NULL, NULL, 3, 1, 1, 1, 0, '2023-09-02 14:46:55', 'sys', '2024-09-20 10:27:31', 'sys');
INSERT INTO `apollo_wenzhou_dev`.`sys_dict` (`id`, `parent_id`, `group_code`, `group_name`, `data_type`, `data_type_name`, `data_tags`, `data_code`, `data_name`, `data_value`, `universal_standard_code`, `remark`, `sort`, `allow_edit`, `version`, `state`, `is_delete`, `create_date_time`, `create_name`, `modify_date_time`, `modify_name`) VALUES (37, 'system', 'project', '工程', 'sectionType', '标段类型', 'project|1', 'construction', '施工', 'construction', NULL, NULL, 1, 1, 1, 1, 0, '2023-09-02 14:46:55', 'sys', '2024-08-31 15:37:15', 'sys');
