### 查询服务
GET http://127.0.0.1:9001/imooc/ecommerce-nacos-client/nacos-client/service-instance?serviceId=e-commerce-gateway
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEsXCJ1c2VybmFtZVwiOlwiUWlueWlAaW1vb2MuY29tXCJ9IiwianRpIjoiNGYyZjU5ODEtZjc1NS00N2MyLWFmNzAtNDY0ZWMzODU4YTVhIiwiZXhwIjoxNjMwMjUyODAwfQ.hnhYM06bkuIESmizQNuN4v0_zXTmAoOYoEgco2h9f5Fi79LiCkNuBmB3r8i6Z_pKjNE99151VIa1gN1hnBF1I3JFWOQobVUtWKk2bs_lpixrZwwhZq8nYtBqbVZwvjyNBXHKUNgOTqBnZOynRJChKwoj1BqNRJ4IPXjl3uQm7ZlWwBG5wtFQpgoAdpLx4DVSpWdqUFKNqm72l-8acnIa2WnP0ifdInvquStcT-19RqbwqoKdbTifXxiiDfZSMQDwOvYyzLYNocVAlIiSlqN3In2OwPBVzCKTnCzX4oatc1eM6AWFYmC_qHpR92A4jD_AVMp8p27DE632stnDfU3fNQ
token: imooc
