server:
  port: 8000
  servlet:
    context-path: /ecommerce-nacos-client

spring:
  application:
    name: commerce-nacos-client
  cloud:
    nacos:
      # 服务注册发现
      discovery:
        enabled: true # 如果不想使用 Nacos 进行服务注册和发现, 设置为 false 即可
        server-addr: 172.16.200.249:8848
        #server-addr: 127.0.0.1:8848
        # server-addr: 127.0.0.1:8848,127.0.0.1:8849,127.0.0.1:8850 # Nacos 服务器地址
        namespace: 1cbd4445-e494-4011-bccb-7ac4c094f9d7
        metadata:
          management:
            context-path: ${server.servlet.context-path}/actuator
          user.name: admin
          user.password: admin
    # sentinel通信
    sentinel:
      transport:
        # sentinel-dashboard-1.6.0 的访问路径 ，启动方式java -jar sentinel-dashboard-1.6.0.jar
        # java -Dserver.port=8082 -jar sentinel-dashboard-1.6.0.jar   默认8080端口
        # Sentinel 控制台地址
        dashboard: localhost:8080
        # 如果有多套网络，又无法正确获取本机IP，则需要使用下面的参数设置当前机器可被外部访问的IP地址，供admin控制台使用
        # spring.cloud.sentinel.transport.client-ip=
        # 应用服务 WEB 访问端口
        #client-ip: 172.16.22.197
        heartbeat-interval-ms: 500
      # 取消Sentinel控制台懒加载
      # 默认情况下 Sentinel 会在客户端首次调用的时候进行初始化，开始向控制台发送心跳包
      # 配置 sentinel.eager=true 时，取消Sentinel控制台懒加载功能
      eager: true
      #开启基于Sentinel的OpenFeign调用限流熔断
      enabled: true


# 暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  file:
    name: nacos-client.log