# 泰康
taikang:
  # 渠道代码
  channelcode: 105000001373
  # 密钥
  signSecret: SgCsHPBPH2121Nn
  # 投保接口
  insureUrl: https://open360uat.tk.cn/open/api/open
  # 百万医疗
  medical:
    # 月缴方案
    monthConfig:
      # 分享链接参数
      tkOpenFrom: 2b86889af2ce89a7c874b14e0b7735829673ae2eba2585a6a2252e5a8aa3d07a
      # 描述
      msg: 百万医疗-月缴方案
      # 产品代码
      productcode: N20240018
      # 月缴等额方案代码
      comboCode: 10N01531
      # 月缴 魔方代码
      discountSubType: 10N01531M001
      # 基础版 保额
      baseTotalAmount: 600000000
      # 升级版 保额
      upgradeTotalAmount: 6000000
      # 基础险别信息
      baseRiskList: "[{\"amount\":3000000,\"kindCode\":\"PYL00310Z326\"},{\"amount\":6000000,\"kindCode\":\"PYL00310Z328\"}]"
      # 升级险别信息
      upgradeRiskList: ""
    # 年缴方案
    yearConfig:
      # 分享链接参数
      tkOpenFrom: 4ae02542388713f1ba4938601c4f8f34143c80f666ca8db88fa34519d8ca7ed5
      # 描述
      msg: 百万医疗-年缴方案
      # 产品代码
      productcode: N20240004
      # 年缴 定额方案代码
      comboCode: 10C01661
      # 年缴 魔方代码
      discountSubType: 10C01661Y001
      # 基础版 保额
      baseTotalAmount: 600000000
      # 升级版 保额
      upgradeTotalAmount: 6000000
      # 基础险别信息
      baseRiskList: "[{\"amount\":3000000,\"kindCode\":\"PYL00310Z326\"},{\"amount\":6000000,\"kindCode\":\"PYL00310Z328\"}]"
      # 升级险别信息
      upgradeRiskList: ""
    # 旅游意外
    travel:
      # 月缴方案
      monthConfig:
      # 年缴方案
      yearConfig:
        # 分享链接参数
        tkOpenFrom: 686473d3ef4589d8e413c5e800f68dd87e651ff3ed6df00ceb4a4b3477b63bfa
        # 描述
        msg: 旅游险-年缴方案
        # 产品代码
        productcode: N20230018
        # 年缴 定额方案代码
        comboCode: 11N00658
        # 基础版 保额
        baseTotalAmount: 326000000
        # 升级版 保额
        upgradeTotalAmount: 326000000
        # 基础险别信息
        baseRiskList: "[{\"amount\":\"15000000\",\"premium\":\"687\",\"kindCode\":\"PYW00050Z674\"},{\"amount\":\"5000000\",\"premium\":\"35\",\"kindCode\":\"PYW00048Z311\"},{\"amount\":\"5000000\",\"premium\":\"152\",\"kindCode\":\"PYW00048Z312\"},{\"amount\":\"5000000\",\"premium\":\"3\",\"kindCode\":\"PYW00048Z305\"},{\"amount\":\"5000000\",\"premium\":\"3\",\"kindCode\":\"PYW00048Z306\"},{\"amount\":\"5000000\",\"premium\":\"4\",\"kindCode\":\"PYW00048Z307\"},{\"amount\":\"5000000\",\"premium\":\"5\",\"kindCode\":\"PYW00048Z308\"},{\"amount\":\"5000000\",\"premium\":\"6\",\"kindCode\":\"PYW00048Z309\"},{\"amount\":\"5000000\",\"premium\":\"7\",\"kindCode\":\"PYW00048Z310\"},{\"amount\":\"100000000\",\"premium\":\"40\",\"kindCode\":\"PYW00047Z541\"},{\"amount\":\"5000000\",\"premium\":\"25\",\"kindCode\":\"AYW00063Z006\"},{\"amount\":\"5000000\",\"premium\":\"38\",\"kindCode\":\"AYW00063Z649\"},{\"amount\":\"3000000\",\"premium\":\"21\",\"kindCode\":\"AYW00043Z698\"}]"
        # 升级险别信息
        upgradeRiskList: ""


person:
  name: sunchao
  age: 12
  birth: 2024/12/12
  map: {k1: v1,k2: v2}
  list: [tom,jack]
  dog:
    name: xiaogou
    age: 2