package com.example.entity;

import java.io.Serializable;
import java.util.Date;

public class Blog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.id
     *
     * @mbg.generated Thu Apr 21 13:52:39 CST 2022
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.title
     *
     * @mbg.generated Thu Apr 21 13:52:39 CST 2022
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.create_date_time
     *
     * @mbg.generated Thu Apr 21 13:52:39 CST 2022
     */
    private Date createDateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.modify_date_time
     *
     * @mbg.generated Thu Apr 21 13:52:39 CST 2022
     */
    private Date modifyDateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.content
     *
     * @mbg.generated Thu Apr 21 13:52:39 CST 2022
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table blog
     *
     * @mbg.generated Thu Apr 21 13:52:39 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated Thu Apr 21 13:52:39 CST 2022
     */
    public Blog(String id, String title, Date createDateTime, Date modifyDateTime) {
        this.id = id;
        this.title = title;
        this.createDateTime = createDateTime;
        this.modifyDateTime = modifyDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated Thu Apr 21 13:52:39 CST 2022
     */
    public Blog(String id, String title, Date createDateTime, Date modifyDateTime, String content) {
        this.id = id;
        this.title = title;
        this.createDateTime = createDateTime;
        this.modifyDateTime = modifyDateTime;
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated Thu Apr 21 13:52:39 CST 2022
     */
    public Blog() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.id
     *
     * @return the value of blog.id
     *
     * @mbg.generated Thu Apr 21 13:52:39 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.id
     *
     * @param id the value for blog.id
     *
     * @mbg.generated Thu Apr 21 13:52:39 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.title
     *
     * @return the value of blog.title
     *
     * @mbg.generated Thu Apr 21 13:52:39 CST 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.title
     *
     * @param title the value for blog.title
     *
     * @mbg.generated Thu Apr 21 13:52:39 CST 2022
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.create_date_time
     *
     * @return the value of blog.create_date_time
     *
     * @mbg.generated Thu Apr 21 13:52:39 CST 2022
     */
    public Date getCreateDateTime() {
        return createDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.create_date_time
     *
     * @param createDateTime the value for blog.create_date_time
     *
     * @mbg.generated Thu Apr 21 13:52:39 CST 2022
     */
    public void setCreateDateTime(Date createDateTime) {
        this.createDateTime = createDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.modify_date_time
     *
     * @return the value of blog.modify_date_time
     *
     * @mbg.generated Thu Apr 21 13:52:39 CST 2022
     */
    public Date getModifyDateTime() {
        return modifyDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.modify_date_time
     *
     * @param modifyDateTime the value for blog.modify_date_time
     *
     * @mbg.generated Thu Apr 21 13:52:39 CST 2022
     */
    public void setModifyDateTime(Date modifyDateTime) {
        this.modifyDateTime = modifyDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.content
     *
     * @return the value of blog.content
     *
     * @mbg.generated Thu Apr 21 13:52:39 CST 2022
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.content
     *
     * @param content the value for blog.content
     *
     * @mbg.generated Thu Apr 21 13:52:39 CST 2022
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated Thu Apr 21 13:52:39 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", title=").append(title);
        sb.append(", createDateTime=").append(createDateTime);
        sb.append(", modifyDateTime=").append(modifyDateTime);
        sb.append(", content=").append(content);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}