spring:
  rabbitmq:
    host: 172.16.200.220
    port: 5672
    username: admin
    password: 123456
    listener:
      simple:
        retry:
          ####开启消费者（程序出现异常的情况下会）进行重试
          enabled: true
          ####最大重试次数
          max-attempts: 5
          ####重试间隔次数
          initial-interval: 3000

logging:
  level:
    com.example: debug