spring:
  application:
    name: web-api
  datasource:
    master:
      jdbc-url: jdbc:mysql://172.16.200.212/anze_biz?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 10
        minimum-idle: 5
        idle-timeout: 600000
        max-lifetime: 1800000
        connection-timeout: 30000

    slave:
      jdbc-url: jdbc:mysql://172.16.200.212/anze_base?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 10
        minimum-idle: 5
        idle-timeout: 600000
        max-lifetime: 1800000
        connection-timeout: 30000


mybatis-plus:
  mapper-locations:
    - classpath:/mapper/*.xml
logging:
  level:
    com.example: debug
server:
  port: 8080
