
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/babybtun?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root123456

  redis:
    host: 127.0.0.1
    port: 6379

  rabbitmq:
    host: 172.16.200.220
    port: 5672
    username: admin
    password: 123456

mybatis-plus:
  mapper-locations:
    - classpath:/mapper/*.xml

logging:
  level:
    com.example: debug
