spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com.example: debug
    com.example.dao: trace
mybatis:
  configuration:
    # ??????
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.entity
