spring:
  application:
    name: log-stack-04

server:
  servlet:
    context-path: /api
  port: 9527

management:
  endpoints:
    web:
      exposure:
        include: "*" # 打开所有的监控点
  endpoint:
    health:
      show-details: always
