server:
  port: 8085
spring:
  cloud:
    alibaba:
      seata:
        tx-service-group: seata-order
  application:
    name: seata-order

seata:
  service:
    vgroup-mapping:
      seata-order: default
    grouplist:
      default: 127.0.0.1:8091
